---
title: "R-HW3"
author: "Margaret He"
date: "April 28th 2016"
output: html_document
---
##Problem I

Estimated Probabilities for 10000 draws
```{r, echo = FALSE}
raceStatus = function(n){
  Gender = sample(c("M","F"),n,replace = TRUE,prob = c(0.55,0.45))
  Race = sapply(1:n,function(i){
    if(Gender[i] =="M"){
      return(sample(c("P","T","Z"),1,prob = c(0.30,0.35,0.35)))
    }else if(Gender[i] =="F"){
      return(sample(c("P","T","Z"),1,prob = c(0.45,0.20,0.35)))
    }else{print("Error")}  
  })
  P.T = sum(Race == "T")/n
  P.ZorM = sum(Race =="Z" | Gender == "M")/n
  P.McgPc = sum(Race !="P" & Gender != "M")/sum(Race != "P")
  P.ZcandMc = sum(Race !="Z" | Gender != "M")/n
  P.MgZ = sum(Race =="Z" & Gender == "M")/sum(Race == "Z")
  Results = matrix(c(P.T,P.ZorM,P.McgPc,P.ZcandMc,P.MgZ),nrow = 1)
  
  colnames(Results)= c("(a):P(Z)","(b):P(M or Z)","(c):P(Mc|Pc)","(d):P(Zc & Mc)", "(e): P(M|Z)")
  rownames(Results) = paste("n =",n)
  return(Results)
}
raceStatus(100000)
```


## Problem II

Corresponding Probabilities:

```{r, echo = FALSE}
suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)

many.hands = sapply(1:1000000,function(i){
  my.hand = deck[,sample(1:52, 2, replace = FALSE)]
  check.a = (my.hand[2,1] == 3 & my.hand[2,2] == 3)
  check.b = (my.hand[1,1] == "S" & my.hand[1,2] == "C")
  check.c = (my.hand[2,1]  == my.hand[2,2])
  
  check.d.1 = (my.hand[2,1] == "Q" & my.hand[1,1] == "S") & (my.hand[2,2] == "J" & my.hand[1,2] == "D")
  
  check.d.2 = (my.hand[2,1] == "J" & my.hand[1,1] == "D") &  (my.hand[2,2] == "Q" & my.hand[1,2] == "S")
  
  check.d = (check.d.1 == TRUE | check.d.2 == TRUE)
  
  all.check = c(check.a,check.b,check.c,check.d)
  names(all.check) = c("(a)","(b)","(c)","(d)")
  return(all.check)
})
rowMeans(many.hands)
```

## Problem III

Estimated Probabilities from 100000 die roll simulations

```{r, echo = FALSE}
roll1 = sample(1:8, 100000, replace = TRUE)
roll2 = sample(1:8, 100000, replace = TRUE)

winnings = 2*roll1-roll2 
```

* (a): Probability you win nothing

```{r, echo = FALSE}
prob.zero = sum(winnings == 0)/(length(roll1)) 
prob.zero
```

* (b): Probability you win at least $2

```{r, echo = FALSE}
prob.min.two = sum(winnings >= 2)/(length(roll1))
prob.min.two
```

* (c): Expected Value of Winnings

```{r, echo = FALSE}
e.v. = mean(winnings)
e.v.
```

* (d): Standard Deviation of Winnings

```{r, echo = FALSE}
std = sd(winnings)
std
```

## Problem IV

Mean and Variance for a discrete random variable

```{r, echo = FALSE}
discrete.rv = function(x,p.x){
  mux = sum(x*p.x)
  sigx =  sum( (x - mux)^2*p.x)
  varx = sigx*sigx
  results = c(mux,varx)
  names(results) = c("Mean","Variance")
  return(results)
}
```

* (a):

```{r, echo = FALSE}
x = c(0,1,2,5,6,10)
p.x = c(0.50,0.05,0.10,0.05,0.05,0.15)
res = round(discrete.rv(x,p.x),digits = 4)

mean = res[1]
mean
var= res[2]
var
```


* (b): 

```{r, echo = FALSE}
x = seq(-20,0,2)
p.x = (1:11)/sum(1:11)
res = round(discrete.rv(x,p.x),digits = 4)

mean = res[1]
mean
var= res[2]
var
```

* (c): 

```{r, echo = FALSE}
x = 0:5
p.x = dbinom(0:5,5,0.50)
res = round(discrete.rv(x,p.x),digits = 4)

mean = res[1]
mean
var= res[2]
var
```

*******

#Code Appendix

```
##Problem I

Estimated Probabilities for 10000 draws

raceStatus = function(n){
  Gender = sample(c("M","F"),n,replace = TRUE,prob = c(0.55,0.45))
  Race = sapply(1:n,function(i){
    if(Gender[i] =="M"){
      return(sample(c("P","T","Z"),1,prob = c(0.30,0.35,0.35)))
    }else if(Gender[i] =="F"){
      return(sample(c("P","T","Z"),1,prob = c(0.45,0.20,0.35)))
    }else{print("Error")}  
  })
  P.T = sum(Race == "T")/n
  P.ZorM = sum(Race =="Z" | Gender == "M")/n
  P.McgPc = sum(Race !="P" & Gender != "M")/sum(Race != "P")
  P.ZcandMc = sum(Race !="Z" | Gender != "M")/n
  P.MgZ = sum(Race =="Z" & Gender == "M")/sum(Race == "Z")
  Results = matrix(c(P.T,P.ZorM,P.McgPc,P.ZcandMc,P.MgZ),nrow = 1)
  
  colnames(Results)= c("(a):P(Z)","(b):P(M or Z)","(c):P(Mc|Pc)","(d):P(Zc & Mc)", "(e): P(M|Z)")
  rownames(Results) = paste("n =",n)
  return(Results)
}
raceStatus(100000)


## Problem II

Corresponding Probabilities:

suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)

many.hands = sapply(1:1000000,function(i){
  my.hand = deck[,sample(1:52, 2, replace = FALSE)]
  check.a = (my.hand[2,1] == 3 & my.hand[2,2] == 3)
  check.b = (my.hand[1,1] == "S" & my.hand[1,2] == "C")
  check.c = (my.hand[2,1]  == my.hand[2,2])
  
  check.d.1 = (my.hand[2,1] == "Q" & my.hand[1,1] == "S") & (my.hand[2,2] == "J" & my.hand[1,2] == "D")
  
  check.d.2 = (my.hand[2,1] == "J" & my.hand[1,1] == "D") &  (my.hand[2,2] == "Q" & my.hand[1,2] == "S")
  
  check.d = (check.d.1 == TRUE | check.d.2 == TRUE)
  
  all.check = c(check.a,check.b,check.c,check.d)
  names(all.check) = c("(a)","(b)","(c)","(d)")
  return(all.check)
})
rowMeans(many.hands)

## Problem III

Estimated Probabilities from 100000 die roll simulations

roll1 = sample(1:8, 100000, replace = TRUE)
roll2 = sample(1:8, 100000, replace = TRUE)

winnings = 2*roll1-roll2 

* (a): Probability you win nothing


prob.zero = sum(winnings == 0)/(length(roll1)) 
prob.zero

* (b): Probability you win at least $2

prob.min.two = sum(winnings >= 2)/(length(roll1))
prob.min.two


* (c): Expected Value of Winnings


e.v. = mean(winnings)
e.v.

* (d): Standard Deviation of Winnings


std = sd(winnings)
std


## Problem IV

Mean and Variances 

discrete.rv = function(x,p.x){
  mux = sum(x*p.x)
  sigx =  sum( (x - mux)^2*p.x)
  varx = sigx*sigx
  results = c(mux,varx)
  names(results) = c("Mean","Variance")
  return(results)
}

* (a):

x = c(0,1,2,5,6,10)
p.x = c(0.50,0.05,0.10,0.05,0.05,0.15)
res = round(discrete.rv(x,p.x),digits = 4)

mean = res[1]
mean
var= res[2]
var


* (b): 

x = seq(-20,0,2)
p.x = (1:11)/sum(1:11)
res = round(discrete.rv(x,p.x),digits = 4)

mean = res[1]
mean
var= res[2]
var

* (c): 

x = 0:5
p.x = dbinom(0:5,5,0.50)
res = round(discrete.rv(x,p.x),digits = 4)

mean = res[1]
mean
var= res[2]
var
```